version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mydrive-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydrive
    volumes:
      - mongodb_data:/data/db
    networks:
      - mydrive-network

volumes:
  mongodb_data:

networks:
  mydrive-network:
    driver: bridge